global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@monitorlegislativo.com'
  smtp_auth_username: 'alerts@monitorlegislativo.com'
  smtp_auth_password: '${SMTP_PASSWORD}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    continue: true
  - match:
      severity: warning
    receiver: 'warning-alerts'
    continue: true
  - match:
      team: backend
    receiver: 'backend-team'
  - match:
      team: devops
    receiver: 'devops-team'

receivers:
- name: 'default'
  email_configs:
  - to: 'devops@monitorlegislativo.com'
    subject: '[Monitor Legislativo] {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Severity:** {{ .Labels.severity }}
      **Time:** {{ .StartsAt }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'critical-alerts@monitorlegislativo.com'
    subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
    body: |
      🚨 CRITICAL ALERT 🚨
      
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Severity:** {{ .Labels.severity }}
      **Time:** {{ .StartsAt }}
      **Runbook:** {{ .Annotations.runbook_url }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-critical'
    title: 'Critical Alert: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      **{{ .Annotations.summary }}**
      {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  pagerduty_configs:
  - service_key: '${PAGERDUTY_SERVICE_KEY}'
    description: '{{ .GroupLabels.alertname }}: {{ .CommonAnnotations.summary }}'

- name: 'warning-alerts'
  email_configs:
  - to: 'warnings@monitorlegislativo.com'
    subject: '[WARNING] {{ .GroupLabels.alertname }}'
    body: |
      ⚠️ WARNING ALERT ⚠️
      
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Severity:** {{ .Labels.severity }}
      **Time:** {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#alerts-warning'
    title: 'Warning: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      {{ .Annotations.summary }}
      {{ .Annotations.description }}
      {{ end }}

- name: 'backend-team'
  email_configs:
  - to: 'backend-team@monitorlegislativo.com'
    subject: '[Backend] {{ .GroupLabels.alertname }}'
    body: |
      Backend Team Alert
      
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Service:** {{ .Labels.service }}
      **Time:** {{ .StartsAt }}
      {{ end }}

- name: 'devops-team'
  email_configs:
  - to: 'devops-team@monitorlegislativo.com'
    subject: '[DevOps] {{ .GroupLabels.alertname }}'
    body: |
      DevOps Team Alert
      
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Infrastructure:** {{ .Labels.instance }}
      **Time:** {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']