apiVersion: v1
kind: Secret
metadata:
  name: monitor-legislativo-secrets
  namespace: monitor-legislativo-production
type: Opaque
stringData:
  # Database Configuration
  DATABASE_URL: "postgresql://monitor_user:${DB_PASSWORD}@monitor-legislativo-cluster.cluster-xyz.us-east-1.rds.amazonaws.com:5432/monitor_legislativo"
  DB_PASSWORD: "${DB_PASSWORD}"
  
  # Redis Configuration
  REDIS_URL: "redis://monitor-legislativo.abc123.cache.amazonaws.com:6379/0"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  
  # Elasticsearch Configuration
  ELASTICSEARCH_URL: "https://search-monitor-legislativo.us-east-1.es.amazonaws.com"
  ELASTICSEARCH_USERNAME: "${ES_USERNAME}"
  ELASTICSEARCH_PASSWORD: "${ES_PASSWORD}"
  
  # External APIs
  CAMARA_API_KEY: "${CAMARA_API_KEY}"
  SENADO_API_KEY: "${SENADO_API_KEY}"
  PLANALTO_API_KEY: "${PLANALTO_API_KEY}"
  
  # JWT and Security
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  SECRET_KEY: "${SECRET_KEY}"
  
  # Monitoring and Observability
  PROMETHEUS_METRICS_TOKEN: "${PROMETHEUS_METRICS_TOKEN}"
  GRAFANA_API_KEY: "${GRAFANA_API_KEY}"
  
  # Email/SMTP Configuration
  SMTP_HOST: "smtp.ses.us-east-1.amazonaws.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  
  # Application Configuration
  FLASK_ENV: "production"
  DEBUG: "false"
  TESTING: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-legislativo-config
  namespace: monitor-legislativo-production
data:
  # Application Settings
  APP_NAME: "Monitor Legislativo"
  APP_VERSION: "1.0.0"
  TIMEZONE: "America/Sao_Paulo"
  LANGUAGE: "pt-BR"
  
  # Performance Settings
  WORKER_PROCESSES: "4"
  MAX_CONNECTIONS: "1000"
  REQUEST_TIMEOUT: "30"
  
  # Cache Settings
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  
  # Rate Limiting
  RATE_LIMIT_PER_MINUTE: "100"
  RATE_LIMIT_BURST: "200"
  
  # Monitoring
  METRICS_ENABLED: "true"
  HEALTH_CHECK_ENABLED: "true"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  LOG_MAX_FILES: "10"
  LOG_MAX_SIZE: "100MB"
  
  # External API Settings
  API_TIMEOUT: "30"
  API_RETRY_COUNT: "3"
  API_BACKOFF_FACTOR: "2"
  
  # Search Configuration
  SEARCH_MAX_RESULTS: "1000"
  SEARCH_TIMEOUT: "10"
  
  # Backup Settings
  BACKUP_ENABLED: "true"
  BACKUP_SCHEDULE: "0 2 * * *"
  BACKUP_RETENTION_DAYS: "30"

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: monitor-legislativo-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitor-legislativo-external-secrets
  namespace: monitor-legislativo-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: monitor-legislativo-secrets
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: monitor-legislativo/database
      property: password
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: monitor-legislativo/redis
      property: password
  - secretKey: ES_USERNAME
    remoteRef:
      key: monitor-legislativo/elasticsearch
      property: username
  - secretKey: ES_PASSWORD
    remoteRef:
      key: monitor-legislativo/elasticsearch
      property: password
  - secretKey: JWT_SECRET_KEY
    remoteRef:
      key: monitor-legislativo/application
      property: jwt_secret
  - secretKey: SECRET_KEY
    remoteRef:
      key: monitor-legislativo/application
      property: secret_key
  - secretKey: CAMARA_API_KEY
    remoteRef:
      key: monitor-legislativo/apis
      property: camara_key
  - secretKey: SENADO_API_KEY
    remoteRef:
      key: monitor-legislativo/apis
      property: senado_key
  - secretKey: PLANALTO_API_KEY
    remoteRef:
      key: monitor-legislativo/apis
      property: planalto_key