apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-legislativo-config
  namespace: monitor-legislativo
data:
  APP_NAME: "Monitor Legislativo"
  APP_VERSION: "4.0.0"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # API Configuration
  API_PREFIX: "/api/v1"
  API_TIMEOUT: "30"
  API_RATE_LIMIT: "100"
  API_RATE_LIMIT_WINDOW: "60"
  
  # Cache Configuration
  CACHE_TTL: "3600"
  CACHE_MAX_SIZE: "1000"
  CACHE_EVICTION_POLICY: "LRU"
  
  # Search Configuration
  SEARCH_MAX_RESULTS: "100"
  SEARCH_DEFAULT_PAGE_SIZE: "20"
  SEARCH_FACET_LIMIT: "50"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # External Services
  CAMARA_API_URL: "https://dadosabertos.camara.leg.br/api/v2"
  SENADO_API_URL: "https://legis.senado.leg.br/dadosabertos"
  PLANALTO_BASE_URL: "http://www4.planalto.gov.br/legislacao"
  
  # Feature Flags
  FEATURE_ML_SCORING: "true"
  FEATURE_REAL_TIME_MONITORING: "true"
  FEATURE_SMART_ALERTS: "true"
  FEATURE_EXPORT_API: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-legislativo-nginx
  namespace: monitor-legislativo
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 4096;
        use epoll;
        multi_accept on;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format json_combined escape=json
          '{'
            '"time_local":"$time_local",'
            '"remote_addr":"$remote_addr",'
            '"remote_user":"$remote_user",'
            '"request":"$request",'
            '"status": "$status",'
            '"body_bytes_sent":"$body_bytes_sent",'
            '"request_time":"$request_time",'
            '"http_referrer":"$http_referer",'
            '"http_user_agent":"$http_user_agent"'
          '}';

        access_log /var/log/nginx/access.log json_combined;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 20M;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml application/atom+xml image/svg+xml;

        upstream backend {
            least_conn;
            server monitor-legislativo-api:8000 max_fails=3 fail_timeout=30s;
        }

        server {
            listen 80;
            server_name _;

            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            location /metrics {
                deny all;
            }

            location /api/ {
                proxy_pass http://backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_cache_bypass $http_upgrade;
                proxy_read_timeout 300s;
                proxy_connect_timeout 75s;
            }

            location / {
                root /usr/share/nginx/html;
                try_files $uri $uri/ /index.html;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";
            }

            location ~* \.(jpg|jpeg|png|gif|ico|css|js|pdf|txt)$ {
                root /usr/share/nginx/html;
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
        }
    }