apiVersion: v1
kind: ServiceMonitor
metadata:
  name: monitor-legislativo-api
  namespace: monitor-legislativo
  labels:
    app: monitor-legislativo
    component: api
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: monitor-legislativo
      component: api
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: monitor-legislativo-worker
  namespace: monitor-legislativo
  labels:
    app: monitor-legislativo
    component: worker
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: monitor-legislativo
      component: worker
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: monitor-legislativo-alerts
  namespace: monitor-legislativo
  labels:
    app: monitor-legislativo
    prometheus: kube-prometheus
spec:
  groups:
  - name: monitor-legislativo.rules
    interval: 30s
    rules:
    # API Alerts
    - alert: APIHighErrorRate
      expr: |
        (
          sum(rate(http_requests_total{app="monitor-legislativo",component="api",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{app="monitor-legislativo",component="api"}[5m]))
        ) > 0.05
      for: 5m
      labels:
        severity: critical
        team: backend
      annotations:
        summary: "High error rate on Monitor Legislativo API"
        description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes"
    
    - alert: APIHighLatency
      expr: |
        histogram_quantile(0.95,
          sum(rate(http_request_duration_seconds_bucket{app="monitor-legislativo",component="api"}[5m]))
          by (le)
        ) > 1
      for: 10m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "High latency on Monitor Legislativo API"
        description: "95th percentile latency is {{ $value }}s over the last 5 minutes"
    
    - alert: APIPodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace="monitor-legislativo",container="api"}[15m]) > 0
      for: 5m
      labels:
        severity: critical
        team: backend
      annotations:
        summary: "API Pod is crash looping"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"
    
    # Worker Alerts
    - alert: WorkerQueueBacklog
      expr: |
        redis_queue_length{queue="document_processing"} > 1000
      for: 15m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "High queue backlog for document processing"
        description: "Queue length is {{ $value }} documents"
    
    - alert: WorkerProcessingRate
      expr: |
        rate(documents_processed_total[5m]) < 10
      for: 10m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "Low document processing rate"
        description: "Processing only {{ $value }} documents per second"
    
    # Database Alerts
    - alert: DatabaseConnectionPoolExhausted
      expr: |
        database_connection_pool_available{app="monitor-legislativo"} < 5
      for: 5m
      labels:
        severity: critical
        team: backend
      annotations:
        summary: "Database connection pool nearly exhausted"
        description: "Only {{ $value }} connections available"
    
    - alert: DatabaseSlowQueries
      expr: |
        rate(database_query_duration_seconds_sum[5m]) > 5
      for: 10m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "Database queries running slowly"
        description: "Average query time is {{ $value }}s"
    
    # Cache Alerts
    - alert: CacheHitRateLow
      expr: |
        (
          sum(rate(cache_hits_total[5m]))
          /
          sum(rate(cache_requests_total[5m]))
        ) < 0.8
      for: 15m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "Cache hit rate is low"
        description: "Hit rate is {{ $value | humanizePercentage }}"
    
    # External API Alerts
    - alert: ExternalAPIDown
      expr: |
        up{job="blackbox",instance=~".*camara.leg.br.*|.*senado.leg.br.*|.*planalto.gov.br.*"} == 0
      for: 5m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "External API is down"
        description: "{{ $labels.instance }} is not responding"
    
    - alert: ExternalAPIHighLatency
      expr: |
        probe_duration_seconds{job="blackbox",instance=~".*camara.leg.br.*|.*senado.leg.br.*|.*planalto.gov.br.*"} > 5
      for: 10m
      labels:
        severity: warning
        team: backend
      annotations:
        summary: "External API response time is high"
        description: "{{ $labels.instance }} response time is {{ $value }}s"