apiVersion: v1
kind: Namespace
metadata:
  name: monitor-legislativo
  labels:
    app: monitor-legislativo
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitor-legislativo-quota
  namespace: monitor-legislativo
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: monitor-legislativo-limits
  namespace: monitor-legislativo
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container